# Generated by Django 2.2.3 on 2019-08-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reading',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(default=1),
        ),
    ]
