# Generated by Django 2.2.3 on 2019-08-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0002_lesson'),
        ('unc', '0002_auto_20190802_1624'),
    ]

    operations = [
    ]
