# Generated by Django 2.2.3 on 2019-08-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0007_auto_20190802_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
