# Generated by Django 2.2.3 on 2019-08-03 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0008_auto_20190802_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 12, 10, 39, 624505, tzinfo=utc), editable=False, null=True),
        ),
    ]
