# Generated by Django 2.2.3 on 2019-08-03 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0009_auto_20190803_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 6, 14, 15, 741694), editable=False, null=True),
        ),
    ]
