# Generated by Django 2.2.4 on 2019-08-10 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0015_auto_20190810_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='reading',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 16, 57, 7, 589331), editable=False, null=True),
        ),
    ]
