# Generated by Django 2.2.3 on 2019-08-11 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0016_auto_20190810_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 10, 19, 48, 58, 802992), editable=False, null=True),
        ),
    ]
