# Generated by Django 2.2.4 on 2019-08-13 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0017_auto_20190810_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 14, 15, 21, 272937), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='actual',
            field=models.TextField(default='Test not run yet'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='correct',
            field=models.TextField(default='Test not run yet'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='label',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='num',
            field=models.IntegerField(default=-1),
        ),
    ]
