# Generated by Django 2.2.4 on 2019-08-13 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0018_auto_20190813_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 16, 23, 49, 232581), editable=False, null=True),
        ),
    ]
