# Generated by Django 2.2.4 on 2019-08-13 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0020_auto_20190813_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 13, 17, 20, 5, 525213), editable=False, null=True),
        ),
    ]
