# Generated by Django 2.2.4 on 2019-08-14 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0021_auto_20190813_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='results',
            field=models.TextField(default='Test not run yet'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='transform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 13, 2, 42, 374912), editable=False, null=True),
        ),
    ]
