# Generated by Django 2.2.4 on 2019-08-14 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0022_auto_20190814_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 14, 12, 18, 20, 943844), editable=False, null=True),
        ),
    ]
