# Generated by Django 2.2.4 on 2019-08-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0023_auto_20190814_1218'),
        ('unc', '0022_auto_20190814_1302'),
    ]

    operations = [
    ]
