# Generated by Django 2.2.4 on 2019-08-16 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0025_auto_20190815_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='face',
            field=models.CharField(default='/static/images/happy.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 15, 36, 11, 866884), editable=False, null=True),
        ),
    ]
