# Generated by Django 2.2.4 on 2019-08-16 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0026_auto_20190816_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='face',
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 16, 16, 7, 1, 71871), editable=False, null=True),
        ),
    ]
