# Generated by Django 2.2.4 on 2019-08-17 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0027_auto_20190816_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 10, 33, 18, 402740), editable=False, null=True),
        ),
    ]
