# Generated by Django 2.2.4 on 2019-08-17 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0028_auto_20190817_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 10, 41, 5, 330449), editable=False, null=True),
        ),
    ]
