# Generated by Django 2.2.4 on 2019-08-17 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0029_auto_20190817_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 13, 12, 44, 108967), editable=False, null=True),
        ),
    ]
