# Generated by Django 2.2.4 on 2019-08-17 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0030_auto_20190817_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 13, 13, 20, 592572), editable=False, null=True),
        ),
    ]
