# Generated by Django 2.2.4 on 2019-08-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0034_auto_20190819_0643'),
        ('unc', '0035_auto_20190817_1316'),
    ]

    operations = [
    ]
