# Generated by Django 2.2.4 on 2019-08-20 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0039_auto_20190820_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 15, 35, 50, 107769), editable=False, null=True),
        ),
    ]
