# Generated by Django 2.2.4 on 2019-08-22 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0040_auto_20190820_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 6, 47, 30, 670403), editable=False, null=True),
        ),
    ]
