# Generated by Django 2.2.4 on 2019-08-24 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0041_auto_20190822_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 12, 50, 28, 197239), editable=False, null=True),
        ),
    ]
