# Generated by Django 2.2.4 on 2019-08-24 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0042_auto_20190824_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 13, 2, 23, 579674), editable=False, null=True),
        ),
    ]
