# Generated by Django 2.2.4 on 2019-08-25 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0044_auto_20190824_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 17, 30, 12, 758782, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 11, 30, 12, 757688), editable=False, null=True),
        ),
    ]
