# Generated by Django 2.2.4 on 2019-08-25 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0045_auto_20190825_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 17, 31, 38, 460387, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 17, 31, 38, 459412, tzinfo=utc), editable=False, null=True),
        ),
    ]
