# Generated by Django 2.2.4 on 2019-08-25 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0046_auto_20190825_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 17, 32, 57, 226175, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 17, 32, 57, 225219, tzinfo=utc), editable=False, null=True),
        ),
    ]
