# Generated by Django 2.2.4 on 2019-08-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0047_auto_20190825_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
