# Generated by Django 2.2.4 on 2019-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0048_auto_20190825_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
