# Generated by Django 2.2.4 on 2019-09-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0049_auto_20190825_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('due', models.DateTimeField(default=None, null=True)),
                ('topic', models.CharField(default='none', max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unc.Course')),
            ],
        ),
    ]
