# Generated by Django 2.2.4 on 2019-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0050_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='images',
            field=models.CharField(default='', max_length=200),
        ),
    ]
