# Generated by Django 2.2.4 on 2019-09-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0051_skill_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unc.Student')),
            ],
        ),
    ]
