# Generated by Django 2.2.4 on 2019-10-22 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0053_urlgame_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(editable=False, max_length=100)),
                ('score', models.IntegerField(default=-1)),
                ('date', models.DateTimeField(editable=False, null=True)),
                ('due', models.DateTimeField(editable=False)),
                ('notes', models.TextField(validators=[django.core.validators.MinLengthValidator(100)])),
                ('requirement_labels', models.TextField(default='NONE')),
                ('requirement_1', models.BooleanField(default=False)),
                ('requirement_2', models.BooleanField(default=False)),
                ('requirement_3', models.BooleanField(default=False)),
                ('requirement_4', models.BooleanField(default=False)),
                ('requirement_5', models.BooleanField(default=False)),
                ('requirement_6', models.BooleanField(default=False)),
                ('requirement_7', models.BooleanField(default=False)),
                ('requirement_8', models.BooleanField(default=False)),
                ('requirement_9', models.BooleanField(default=False)),
                ('requirement_10', models.BooleanField(default=False)),
                ('designer', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='unc.Student')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='unc.Student')),
            ],
        ),
    ]
