# Generated by Django 2.2.4 on 2019-11-25 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0055_auto_20191022_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='project',
        ),
        migrations.AlterField(
            model_name='review',
            name='notes',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
