# Generated by Django 2.2.4 on 2019-11-25 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0057_auto_20191125_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 7, 0, tzinfo=utc), null=True),
        ),
    ]
