# Generated by Django 2.2.4 on 2019-11-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0058_auto_20191125_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='zybooks',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
