# Generated by Django 2.2.4 on 2019-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unc', '0059_lesson_zybooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='reading',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='zybooks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
