# Generated by Django 3.0 on 2019-12-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_auto_20191127_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
