# Generated by Django 3.0 on 2019-12-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_auto_20191213_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
