# Generated by Django 3.0 on 2019-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_auto_20191213_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='day',
            field=models.DateField(null=True),
        ),
    ]
