# Generated by Django 3.0 on 2019-12-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_insight_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='date',
        ),
    ]
