# Generated by Django 3.0 on 2019-12-13 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0006_remove_insight_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insight',
            old_name='day',
            new_name='date',
        ),
    ]
